version: '3.8' 
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"  
    volumes:
      - .:/app  
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - WONDERBITS_MONGODB_URI=mongodb://mongo:27017/Wonderbits
      - REDIS_URL=redis://redis:6379  
      - DEPLOYER_PRIVATE_KEY=walletPrivateKey 
    command: ["npx", "ts-node", "server.ts"]  

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data 

volumes:
  mongo-data:
  redis-data:
