import mongoose from 'mongoose';
import { UserSchema } from '../../schemas/User';
import { BitSchema } from '../../schemas/Bit';
import { IslandSchema } from '../../schemas/Island';
import { RaftSchema } from '../../schemas/Raft';
import { CookieDepositSchema, CookieWithdrawalSchema } from '../../schemas/Cookie';
import { QuestSchema } from '../../schemas/Quest';
import { POISchema } from '../../schemas/POI';
import { LeaderboardSchema } from '../../schemas/Leaderboard';
import { StarterCodeSchema } from '../../schemas/Invite';
import { TutorialSchema } from '../../schemas/Tutorial';
import { SquadSchema } from '../../schemas/Squad';
import { SquadLeaderboardSchema, SquadMemberClaimableWeeklyRewardSchema } from '../../schemas/SquadLeaderboard';
import { SettingSchema } from '../../schemas/Setting';
import { POAPSchema } from '../../schemas/POAP';
import { KOSClaimableDailyRewardsSchema, KOSClaimableWeeklyRewardsSchema } from '../../schemas/KOSRewards';
import { WeeklyMVPClaimableRewardSchema, WeeklyMVPRankingLeaderboardSchema } from '../../schemas/WeeklyMVPReward';
import { CollabSchema } from '../../schemas/Collab';
import { CollabBasketSchema, CollabParticipantSchema } from '../../schemas/CollabV2';

export const UserModel = mongoose.model('Users', UserSchema, 'Users');
export const BitModel = mongoose.model('Bits', BitSchema, 'Bits');
export const IslandModel = mongoose.model('Islands', IslandSchema, 'Islands');
export const RaftModel = mongoose.model('Rafts', RaftSchema, 'Rafts');
export const CookieDepositModel = mongoose.model('CookieDeposits', CookieDepositSchema, 'CookieDeposits');
export const CookieWithdrawalModel = mongoose.model('CookieWithdrawals', CookieWithdrawalSchema, 'CookieWithdrawals');
export const QuestModel = mongoose.model('Quests', QuestSchema, 'Quests');
export const POIModel = mongoose.model('POI', POISchema, 'POI');
export const LeaderboardModel = mongoose.model('Leaderboards', LeaderboardSchema, 'Leaderboards');
export const StarterCodeModel = mongoose.model('StarterCodes', StarterCodeSchema, 'StarterCodes');
export const TutorialModel = mongoose.model('Tutorials', TutorialSchema, 'Tutorials');
export const SquadModel = mongoose.model('Squads', SquadSchema, 'Squads');
export const SquadLeaderboardModel = mongoose.model('SquadLeaderboards', SquadLeaderboardSchema, 'SquadLeaderboards');
export const SettingModel = mongoose.model('Settings', SettingSchema, 'Settings');
export const POAPModel = mongoose.model('POAP', POAPSchema, 'POAP');
export const KOSClaimableDailyRewardsModel = mongoose.model('KOSClaimableDailyRewards', KOSClaimableDailyRewardsSchema, 'KOSClaimableDailyRewards');
export const KOSClaimableWeeklyRewardsModel = mongoose.model('KOSClaimableWeeklyRewards', KOSClaimableWeeklyRewardsSchema, 'KOSClaimableWeeklyRewards');
export const WeeklyMVPClaimableRewardsModel = mongoose.model('WeeklyMVPClaimableRewards', WeeklyMVPClaimableRewardSchema, 'WeeklyMVPClaimableRewards');
export const SquadMemberClaimableWeeklyRewardModel = mongoose.model('SquadMemberClaimableWeeklyRewards', SquadMemberClaimableWeeklyRewardSchema, 'SquadMemberClaimableWeeklyRewards');
export const CollabModel = mongoose.model('Collabs', CollabSchema, 'Collabs');
export const CollabParticipantModel = mongoose.model('CollabParticipants', CollabParticipantSchema, 'CollabParticipants');
export const CollabBasketModel = mongoose.model('CollabBaskets', CollabBasketSchema, 'CollabBaskets');
export const WeeklyMVPRankingLeaderboardModel = mongoose.model('WeeklyMVPRankingData', WeeklyMVPRankingLeaderboardSchema, 'WeeklyMVPRankingData');
