/**
 * Represents an invite code's data used to play the game (or works as a referral code).
 */
export interface InviteCodeData {
    /** the type of invite code */
    type: InviteCodeType,
    /** the code itself */
    code: string,
    /** 
     * if the invite code type is referral, a referrerId is specified
     * 
     * this is the database ID of the user who referred the user to sign up
     */
    referrerId?: string,
    /** 
     * the amount of uses the code can provide.
     * 
     * referral codes are infinite. however, starter codes may have a limit.
     */
    maxUses: number | 'infinite';
    /**
     * a list of user IDs who have used the code.
     * 
     * if this code is a starter code, this is used to check if the code has reached its limit.
     */
    usedBy: string[]
}

/**
 * Represents a starter code's data.
 */
export interface StarterCodeData {
    /** the code itself */
    code: string,
    /** 
     * the amount of uses the code can provide.
     * 
     * starter codes may have a limit or can be infinite.
     */
    maxUses: number | 'infinite',
    /** a list of user IDs who have used the code */
    usedBy: string[]
}

/**
 * Represents the type of invite code.
 */
export enum InviteCodeType {
    /** referral codes are obtained from other users */
    REFERRAL = 'Referral',
    /** starter codes are generated by NBC */
    STARTER = 'Starter'
}