import { FoodType } from './food';
import { SmeltingItem, SynthesizingItem } from './item';
import { User } from './user';

/**
 * Represents the purchase details for a trade listing.
 */
export interface PurchaseDetails {
    user: User | string;
    amount: number;
    purchasedTimestamp: number;
    claimed: boolean;
}

/**
 * Represents a trade listing.
 */
export interface TradeListing {
    /** The unique ID of the trade listing, generated by the database */
    _id?: string;
    /** The user who created (sold) the trade listing */
    user: User | string;
    /** The user who purchased the trade listing */
    purchasedBy?: PurchaseDetails[];
    /** The item being traded */
    item: ItemType;
    /** The amount of the item being traded */
    amount: number;
    /** The price per item */
    price: number;
    /** The currency used for the trade */
    currency: TradeCurrency;
    /** The current status of the trade */
    status: TradeStatus;
    /** The timestamp when the trade was listed */
    listedTimestamp: number;
}

/**
 * Represents a trade listing item type.
 */
export type ItemType = FoodType | SynthesizingItem | SmeltingItem;

/**
 * Represents the status of a trade listing.
 */
export enum TradeStatus {
    ACTIVE = 'Active', // Listed and available for purchase
    SOLD = 'Sold', // Purchased by someone but not yet claimed by the seller
    COMPLETED = 'Completed', // Seller has claimed the listed price
}

/**
 * Represents the supported currencies for trade.
 */
export enum TradeCurrency {
    X_COOKIES = 'xCookies',
}
