import { Food } from './food';
import { Item } from './item';
import { Resource } from './resource';

/****************
 * USER-RELATED MODELS
 ****************/

/**
 * Represents a user.
 */
export interface User {
    /** the unique ID of the user, generated by the database */
    id: string;
    /** the twitter user ID of the user */
    twitterId: string;
    /** the user's wallet data, created when the user signs up for the first time */
    wallet: UserWallet;
    /** a list of tweet IDs where chests have been opened for today */
    openedTweetIdsToday: string[];
    /** the user's inventory */
    inventory: UserInventory;
}

/**
 * Represents a user's Web3 wallet.
 */
export interface UserWallet {
    /** the wallet's public key, i.e. address */
    publicKey: string;
    /** the wallet's private key used to export the wallet */
    privateKey: string;
}

/**
 * Represents a user's inventory.
 */
export interface UserInventory {
    /** the amount of in-game cookies (users are required to convert from blockchain cookies first) */
    xCookies: number;
    /** a list of resources owned */
    ownedResources: Resource[];
    /** a list of items owned */
    ownedItems: Item[];
    /** a list of foods owned */
    ownedFoods: Food[];
    /** the owned raft ID */
    ownedRaftId: number;
    /** a list of owned island IDs */
    ownedIslandIds: number[];
    /** a list of owned bit IDs */
    ownedBitIds: number[];
    /** a list of owned bit orb IDs */
    ownedBitOrbIds: number[];
    /** a list of owned terra capsulator IDs */
    ownedTerraCapsulatorIds: number[];
}