import { POIName } from './poi';
import { Food } from './food';
import { Item } from './item';
import { ExtendedResource } from './resource';
import { InviteCodeData, ReferralData } from './invite';

/****************
 * USER-RELATED MODELS
 ****************/

/**
 * Represents a user.
 */
export interface User {
    /** the unique ID of the user, generated by the database */
    userId: string;
    /** the twitter user ID of the user */
    twitterId: string;
    /** the user's twitter profile picture URL */
    twitterProfilePicture: string;
    /** when the account was created */
    createdTimestamp: number;
    /** 
     * the invite code used for the user to play the game 
     * 
     * if the user signed up via a referral code, the referrer's id is stored here.
     */
    inviteCodeData: InviteCodeData;
    /** the user's personal referral data (including their code, the amount of people they referred and so on) */
    referralData: ReferralData;
    /** the user's wallet data, created when the user signs up for the first time */
    wallet: UserWallet;
    /** users can link up to 10 secondary wallets. this contains the data of each secondary wallet instance, such as the signature. */
    secondaryWallets?: UserSecondaryWallet[];
    /** a list of tweet IDs where chests have been opened for today */
    openedTweetIdsToday: string[];
    /** the user's inventory */
    inventory: UserInventory;
    /** the user's in-game data */
    inGameData: InGameData;
}

/**
 * Represents a user's Web3 wallet.
 */
export interface UserWallet {
    /** the wallet's public key, i.e. address */
    publicKey: string;
    /** the wallet's private key used to export the wallet */
    privateKey: string;
}

/**
 * Represents a user's secondary wallet that they can link to their account.
 */
export interface UserSecondaryWallet {
    /** the message used to generate the signature for verification */
    signatureMessage: string;
    /** the signature of the user from the secondary wallet, showing ownership of the wallet */
    signature: string;
    /** the secondary wallet's public key, i.e. address */
    publicKey: string;
}

/**
 * Represents a user's inventory.
 */
export interface UserInventory {
    /** the weight of the inventory (currently only impacted by resources) */
    weight: number;
    /** the maximum inventory weight the user can have */
    maxWeight: number;
    /** the amount of in-game cookies owned (users are required to convert from blockchain cookies first) */
    xCookies: number;
    /** the amount of cookie crumbs owned */
    cookieCrumbs: number;
    /** a list of resources owned */
    resources: ExtendedResource[];
    /** a list of items owned */
    items: Item[];
    /** a list of foods owned */
    foods: Food[];
    /** the owned raft ID */
    raftId: number;
    /** a list of owned island IDs */
    islandIds: number[];
    /** a list of owned bit IDs */
    bitIds: number[];    
    /** total amount of bit orbs owned */
    totalBitOrbs: number;
    /** total amount of terra caps owned */
    totalTerraCapsulators: number;
}

/**
 * Represents the user's in-game data
 */
export interface InGameData {
    /** the user's level */
    level: number;
    /** the list of tutorial IDs the user has completed at the start */
    completedTutorialIds: number[];
    /** 
     * the user's beginner reward data 
     * 
     * this is a 7-day reward system when the user signs up for the first time.
     */
    beginnerRewardData: BeginnerRewardData;
    /** the user's daily login reward data */
    dailyLoginRewardData: DailyLoginRewardData;
    /** the current location of the user (either home or in a POI) */
    location: POIName;
    /** 
     * checks if the user is currently travelling to another POI 
     * 
     * if not null, this means that the user is currently travelling to another POI.
     */
    travellingTo: POIName | null;
    /** 
     * the arrival time of the destination at `travellingTo`
     * 
     * value will be 0 if not travelling (i.e. if travellingTo is null)
     */
    destinationArrival: number;
}

/**
 * Represents the user's beginner reward data.
 */
export interface BeginnerRewardData {
    /** the last claimed timestamp of the beginner reward */
    lastClaimedTimestamp: number;
    /** 
     * checks if the beginner reward is claimable.
     * 
     * this is true by default and will be set to false if the user has claimed the reward for the day.
     * 
     * the scheduler will reset this to true every day at 00:00 UTC.
     */
    isClaimable: boolean;
    /**
     * the days the user has claimed the beginner rewards.
     * 
     * if a user misses a day (i.e. not claiming the beginner rewards between 00:00 - 23:59 of that day, the day will be added to `daysMissed`).
     */
    daysClaimed: number[];
    /**
     * the days the user has missed claiming the beginner rewards.
     */
    daysMissed: number[];
}

/**
 * Represents the user's daily login reward data.
 * 
 * Doesn't require storing rewards earned here, as the rewards are fixed and can be calculated based on the consecutive days (for now).
 */
export interface DailyLoginRewardData {
    /** the last claimed timestamp of the daily login reward */
    lastClaimedTimestamp: number;
    /** 
     * checks if the daily login reward is claimable.
     * 
     * this is true by default and will be set to false if the user has claimed the reward for the day.
     * 
     * the scheduler will reset this to true every day at 00:00 UTC.
     */
    isDailyClaimable: boolean;
    /** the amount of consecutive days the user claimed the rewards */
    consecutiveDaysClaimed: number;
}

/**
 * Represents the daily login reward.
 */
export interface DailyLoginReward {
    /** the type of reward */
    type: DailyLoginRewardType;
    /** the amount of reward */
    amount: number;
}

/**
 * Represents the type of daily login reward.
 */
export enum DailyLoginRewardType {
    X_COOKIES = 'xCookies',
    LEADERBOARD_POINTS = 'Leaderboard Points',
}

/**
 * Represents the beginner reward.
 */
export interface BeginnerReward {
    /** the type of reward */
    type: BeginnerRewardType;
    /** the amount of reward */
    amount: number;
}

/**
 * Represents the type of beginner reward.
 */
export enum BeginnerRewardType {
    X_COOKIES = 'xCookies',
    BIT_ORB = 'Bit Orb',
    TERRA_CAPSULATOR = 'Terra Capsulator',
}
